-- Nome: Felipe Andrade Martins
-- Matrícula: 635093PRIMARY
use BD;
-- Questão01
CREATE TABLE AUTOR (
    NOMEAUT VARCHAR(100) NOT NULL,
    CODIGO INT NOT NULL,
    PRIMARY KEY (CODIGO),
    UNIQUE (NOMEAUT)
);
    
CREATE TABLE EDITORA (
    NOMEEDIT VARCHAR(100) NOT NULL,
    CODIGO INT NOT NULL,
    PRIMARY KEY (CODIGO),
    UNIQUE (NOMEEDIT)
);

CREATE TABLE ASSUNTO (
    DESCRICAO VARCHAR(100) NOT NULL,
    CODIGO INT NOT NULL,
    PRIMARY KEY (CODIGO),
    UNIQUE (DESCRICAO)
);

CREATE TABLE LIVRO (
    CODIGO INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    ANOPUBLIC DATE,
    CODEDIT INT NOT NULL,
    CODASSUNTO INT NOT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE AUTORIA (
    CODLIVRO INT NOT NULL,
    CODAUTOR INT NOT NULL,
    PRIMARY KEY (CODAUTOR),
    FOREIGN KEY (CODLIVRO)
        REFERENCES LIVRO (CODIGO)
);

CREATE TABLE EXEMPLAR (
    CODEXEMPLAR INT NOT NULL,
    CODLLIVRO INT NOT NULL,
    DATAAQUISICAO DATE NOT NULL,
    VALORAQUISICAO FLOAT,
    PRIMARY KEY (CODEXEMPLAR)
);

CREATE TABLE EMPRESTIMO (
    CODEMPREST INT NOT NULL,
    DATA DATE,
    CODALUNO INT,
    PRIMARY KEY (CODEMPREST)
);

CREATE TABLE ITEMEMPREST (
    CODEMPRESTITEM INT NOT NULL,
    CODEXEMPLAR INT NOT NULL,
    DATADEVOLUCAO DATE NOT NULL,
    MULTA FLOAT,
    FOREIGN KEY (CODEMPRESTITEM)
        REFERENCES EMPRESTIMO (CODEMPREST)
);


CREATE TABLE ALUNO (
    CODIGO INT NOT NULL,
    NOME TEXT NOT NULL,
    DATANASC DATE NOT NULL,
    CIDADE TEXT NOT NULL,
    PRIMARY KEY (CODIGO)
);

-- Questão 02

INSERT INTO AUTOR
    VALUES ("CLEITON VERGAS", 1);

INSERT INTO AUTOR
    VALUES ("CHICO TORRESMO", 2);
    
INSERT INTO AUTOR
    VALUES ("NILSON FREITAS", 3);
    
INSERT INTO AUTOR
    VALUES ("MILTON MOURÃO", 4);
    
INSERT INTO AUTOR
    VALUES ("NIKOLAI LESKOV", 5);
    
INSERT INTO AUTOR
    VALUES ("RUBINHO KERENINA", 6);
    
INSERT INTO AUTOR
    VALUES ("LIEV TOLSTOI", 7);

INSERT INTO EDITORA
    VALUES ("VEJA", 1);

INSERT INTO EDITORA
    VALUES ("FUI", 2);
    
INSERT INTO EDITORA
    VALUES ("YOU", 3);
    
INSERT INTO EDITORA
    VALUES ("TOPS DOS TOPS", 4);
    
INSERT INTO EDITORA
    VALUES ("EDITORA TOIS", 5);

INSERT INTO ASSUNTO
    VALUES ("ROMANCE", 1);

INSERT INTO ASSUNTO
    VALUES ("LITERATURA BRASILEIRA", 2);
    
INSERT INTO ASSUNTO
    VALUES ("COMÉDIA", 3);
    
INSERT INTO ASSUNTO
    VALUES ("TERROR", 4);
    
INSERT INTO ASSUNTO
    VALUES ("ERÓTICO", 5);


-- INSERT EM LIVROS
INSERT INTO LIVRO
    VALUES (1, "MEMÓRIAS PÓSTUMAS DE UM ALUNO DA COMPUTAÇÃO", '2019', 1, 1);

-- Questão 03

-- SELECT L.NOME, L.ANOPUBLIC, E.COUT(EXEMPLAR), E.AVG(VALORAQUISICAO) FROM LIVRO AS L, EXEMPLAR AS E 
   --  WHERE L.ANOPUBLIC = '2019' AND L.ASSUNTO = "LITERATURA BRASILEIRA";
