--Nome: Felipe Andrade Martins
CREATE TABLE AUTOR
(
	NOMEAUT VARCHAR(100)	NOT NULL,
	CODIGO	INT				NOT NULL,
	PRIMARY KEY (CODIGO),
	UNIQUE (NOMEAUT)
);
    
CREATE TABLE EDITORA
(
	CODIGO	 INT			NOT NULL,	
	NOMEEDIT VARCHAR(100)	NOT NULL,
	PRIMARY KEY (CODIGO),
	UNIQUE (NOMEEDIT)
);

CREATE TABLE ASSUNTO
(
	CODIGO	  INT			NOT NULL,	
	DESCRICAO VARCHAR(100)	NOT NULL,
	PRIMARY KEY (CODIGO),
	UNIQUE (DESCRICAO)
);

CREATE TABLE LIVRO
(
	CODIGO	   INT			NOT NULL,	
	TITULO     VARCHAR(100)	NOT NULL,
	ANOPUBLIC  DATE,
	CODEDIT    INT			NOT NULL,
	CODASSUNTO INT			NOT NULL,

	PRIMARY KEY (CODIGO),	
);

CREATE TABLE AUTORIA
(
	CODLIVRO INT NOT NULL,
	CODAUTOR INT NOT NULL,
	PRIMARY KEY (CODAUTOR),
	FOREIGN KEY (CODLIVRO) REFERENCES LIVRO(CODIGO)
);

CREATE TABLE EXEMPLAR
(
	CODEXEMPLAR    INT  NOT NULL,
	CODLLIVRO      INT  NOT NULL,
	DATAAQUISICAO  DATE NOT NULL,
	VALORAQUISICAO FLOAT,
	PRIMARY KEY (CODEXEMPLAR),	
);

CREATE TABLE EMPRESTIMO
(
	CODEMPREST INT  NOT NULL,
	DATA		DATE,
	CODALUNO    INT, 
	PRIMARY KEY (CODEMPREST)
);

CREATE TABLE ITEMEMPREST
(
	CODEMPRESTITEM INT  NOT NULL,
	CODEXEMPLAR    INT  NOT NULL,
	DATADEVOLUCAO  DATE NOT NULL,
	MULTA FLOAT,
	FOREIGN KEY (CODEMPRESTITEM) REFERENCES EMPRESTIMO(CODEMPREST)
);


CREATE TABLE ALUNO
(
	CODIGO   INT  NOT NULL,
	NOME     TEXT NOT NULL,
	DATANASC DATE NOT NULL,
	CIDADE   TEXT NOT NULL,

	PRIMARY  KEY (CODIGO)
);


---Selecionar o título, ano publicação, quantidade de exemplares e valor médio de aquisição dos
---livros adquiridos no ano de 2019, cujo assunto seja “Literatura Brasileira”.